window.words=[

{jp:"りんご",en:"apple",rank:1},
{jp:"ねこ",en:"cat",rank:1},
{jp:"いぬ",en:"dog",rank:1},
{jp:"バナナ",en:"banana",rank:1},
{jp:"本",en:"book",rank:1},
{jp:"箱",en:"box",rank:1},
{jp:"星",en:"star",rank:1},
{jp:"あお",en:"blue",rank:1},
{jp:"あか",en:"red",rank:1},
{jp:"そら",en:"sky",rank:1},
{jp:"水",en:"water",rank:1},
{jp:"火",en:"fire",rank:1},
{jp:"木",en:"tree",rank:1},
{jp:"海",en:"sea",rank:1},
{jp:"太陽",en:"sun",rank:1},
{jp:"月",en:"moon",rank:1},

{jp:"車",en:"car",rank:1},
{jp:"電車",en:"train",rank:1},
{jp:"家(建物)",en:"house",rank:2},
{jp:"家(家庭・我が家)",en:"home",rank:1},
{jp:"窓",en:"window",rank:1},
{jp:"ドア",en:"door",rank:1},

{jp:"かばん",en:"bag",rank:1},
{jp:"靴",en:"shoe",rank:3},
{jp:"シャツ",en:"shirt",rank:3},

{jp:"手",en:"hand",rank:1},
{jp:"足",en:"foot",rank:3},
{jp:"目",en:"eye",rank:1},
{jp:"耳",en:"ear",rank:3},
{jp:"口",en:"mouth",rank:2},
{jp:"顔",en:"face",rank:1},

{jp:"男",en:"man",rank:1},
{jp:"女",en:"woman",rank:1},
{jp:"子供",en:"child",rank:1},
{jp:"赤ちゃん",en:"baby",rank:1},
{jp:"父",en:"father",rank:1},
{jp:"母",en:"mother",rank:1},
{jp:"兄",en:"brother",rank:1},
{jp:"姉",en:"sister",rank:1},

{jp:"食べる",en:"eat",rank:1},
{jp:"飲む",en:"drink",rank:1},
{jp:"行く",en:"go",rank:1},
{jp:"来る",en:"come",rank:1},
{jp:"見る(自然に見える)",en:"see",rank:1},
{jp:"見る(意識して見る)",en:"watch",rank:2},
{jp:"見る(視線を向ける)",en:"look at",rank:2},
{jp:"聞こえる",en:"hear",rank:1},
{jp:"聞く(耳を傾ける)",en:"listen to",rank:2},
{jp:"読む",en:"read",rank:1},
{jp:"書く",en:"write",rank:1},

{jp:"大きい",en:"big",rank:1},
{jp:"小さい",en:"small",rank:1},
{jp:"新しい",en:"new",rank:1},
{jp:"古い",en:"old",rank:1},
{jp:"速い",en:"fast",rank:2},
{jp:"遅い",en:"slow",rank:2},
{jp:"暑い/熱い",en:"hot",rank:1},
{jp:"寒い",en:"cold",rank:1},

{jp:"学校",en:"school",rank:1},
{jp:"時間/回数",en:"time",rank:2},
{jp:"ベッド",en:"bed",rank:1},
{jp:"みどり",en:"green",rank:1},
{jp:"花",en:"flower",rank:2},
{jp:"数学",en:"math",rank:2},
{jp:"英語",en:"english",rank:2},
{jp:"金曜日",en:"friday",rank:1},
{jp:"日曜日",en:"sunday",rank:1},
{jp:"月曜日",en:"monday",rank:2},
{jp:"鉱物",en:"mineral",rank:3},
{jp:"家族",en:"family",rank:2},
{jp:"部屋/空間",en:"room",rank:2},
{jp:"机",en:"desk",rank:2},
{jp:"椅子",en:"chair",rank:2},
{jp:"公園",en:"park",rank:2},
{jp:"病院",en:"hospital",rank:2},
{jp:"駅",en:"station",rank:2},
{jp:"川",en:"river",rank:2},
{jp:"山",en:"mountain",rank:2},
{jp:"雨",en:"rain",rank:2},
{jp:"雪",en:"snow",rank:2},
{jp:"朝",en:"morning",rank:2},
{jp:"夜",en:"night",rank:2},
{jp:"走る/運営する",en:"run",rank:2},
{jp:"歩く",en:"walk",rank:2},
{jp:"大きい/重要な",en:"big",rank:2},
{jp:"小さい/幼い",en:"small",rank:2},

{jp:"火曜日",en:"tuesday",rank:2},
{jp:"友達",en:"friend",rank:2},
{jp:"土曜日",en:"saturday",rank:2},
{jp:"毒",en:"poison",rank:3},
{jp:"霧(湿度が高い)",en:"mist",rank:3},
{jp:"鉱山/採掘する",en:"mine",rank:3},
{jp:"恐竜",en:"dinosaur",rank:4},
{jp:"たんぱく質",en:"protein",rank:3},
{jp:"顕微鏡",en:"microscope",rank:3},
{jp:"クローン",en:"clone",rank:3},
{jp:"発光ダイオード",en:"LED",rank:3},
{jp:"町",en:"town",rank:2},
{jp:"村",en:"village",rank:3},
{jp:"橋/架け橋",en:"bridge",rank:2},
{jp:"森",en:"forest",rank:3},
{jp:"湖",en:"lake",rank:3},
{jp:"島",en:"island",rank:3},
{jp:"動物",en:"animal",rank:2},
{jp:"植物/工場",en:"plant",rank:3},
{jp:"季節",en:"season",rank:2},
{jp:"天気",en:"weather",rank:2},
{jp:"旅行/移動",en:"travel",rank:2},
{jp:"休日/祝日",en:"holiday",rank:2},
{jp:"健康",en:"health",rank:3},
{jp:"未来",en:"future",rank:3},
{jp:"過去/過ぎた",en:"past",rank:4},
{jp:"考える/思う",en:"think",rank:2},
{jp:"学ぶ/知る",en:"learn",rank:2},
{jp:"作る/創造する",en:"create",rank:3},
{jp:"始める",en:"begin",rank:2},
{jp:"終える/仕上げる",en:"finish",rank:2},

{jp:"先生",en:"teacher",rank:2},
{jp:"水曜日",en:"wednesday",rank:3},
{jp:"木曜日",en:"thursday",rank:3},
{jp:"層/階層",en:"layer",rank:4},
{jp:"光線/線",en:"ray",rank:4},
{jp:"測る",en:"measure",rank:4},
{jp:"危険(潜在)",en:"hazard",rank:4},
{jp:"循環",en:"circulate",rank:4},
{jp:"日陰/陰",en:"shade",rank:4},
{jp:"生成する/生み出す",en:"generate",rank:4},
{jp:"不足している",en:"scarce",rank:4},
{jp:"持続可能な",en:"sustainable",rank:4},
{jp:"無限の",en:"infinite",rank:4},
{jp:"居住可能な",en:"habitable",rank:4},
{jp:"復活させる",en:"revive",rank:4},
{jp:"繁殖する",en:"reproduce",rank:4},
{jp:"巣",en:"nest",rank:4},
{jp:"生物/生き物",en:"creature",rank:4},
{jp:"骨格",en:"skeleton",rank:4},
{jp:"雑種",en:"hybrid",rank:4},
{jp:"目に見える",en:"visible",rank:4},
{jp:"寄生生物",en:"parasite",rank:4},
{jp:"進化",en:"evolution",rank:4},
{jp:"分類する",en:"sort",rank:4},
{jp:"解剖学",en:"anatomy",rank:4},
{jp:"王国/界",en:"kingdom",rank:4},
{jp:"マンモス",en:"mammoth",rank:4},
{jp:"まねる/模倣する",en:"mimic",rank:4},
{jp:"温室",en:"greenhouse",rank:4},
{jp:"原子",en:"atom",rank:4},
{jp:"固体/固形物",en:"solid",rank:4},
{jp:"溶ける",en:"melt",rank:4},
{jp:"仕掛け",en:"gimmick",rank:4},
{jp:"知識",en:"knowledge",rank:5},
{jp:"情報",en:"information",rank:4},
{jp:"研究/調査",en:"research",rank:4},
{jp:"技術/科学技術",en:"technology",rank:4},
{jp:"発明",en:"invention",rank:5},
{jp:"発見",en:"discovery",rank:4},
{jp:"原因/引き起こすもの",en:"cause",rank:3},
{jp:"結果",en:"result",rank:3},
{jp:"方法/手法",en:"method",rank:4},
{jp:"目的/意図",en:"purpose",rank:4},
{jp:"課題/問題",en:"issue",rank:4},
{jp:"責任",en:"responsibility",rank:6},
{jp:"機会/好機",en:"opportunity",rank:6},
{jp:"資源/資産",en:"resource",rank:4},
{jp:"保護する/守る",en:"protect",rank:4},
{jp:"減少する/減る",en:"decrease",rank:4},
{jp:"増加する/増える",en:"increase",rank:4},
{jp:"比較する/比べる",en:"compare",rank:6},
{jp:"説明する/解説する",en:"explain",rank:5},

{jp:"紫外線",en:"ultraviolet",rank:5},
{jp:"経済",en:"economy",rank:5},
{jp:"哲学",en:"philosophy",rank:5},
{jp:"北極",en:"arctic",rank:5},
{jp:"南極",en:"antarctic",rank:5},
{jp:"発する/放出する",en:"emit",rank:5},
{jp:"議定書",en:"protocol",rank:5},
{jp:"浸食/侵食",en:"erosion",rank:5},
{jp:"大災害",en:"catastrophe",rank:5},
{jp:"干ばつ/旱魃",en:"drought",rank:5},
{jp:"湿った",en:"moist",rank:5},
{jp:"浸す/染み込ませる",en:"soak",rank:5},
{jp:"噴火する/噴出する",en:"erupt",rank:5},
{jp:"有限の/限りある",en:"finite",rank:5},
{jp:"獲物/えじき",en:"prey",rank:5},
{jp:"遺伝",en:"heredity",rank:5},
{jp:"噛む",en:"bite",rank:5},
{jp:"種/種子",en:"seed",rank:5},
{jp:"無数の",en:"myriad",rank:5},
{jp:"収穫する",en:"harvest",rank:5},
{jp:"土壌",en:"soil",rank:5},
{jp:"蒸気/水蒸気",en:"vapor",rank:5},
{jp:"真空",en:"vacuum",rank:5},
{jp:"浮く/漂う",en:"float",rank:5},
{jp:"観察する",en:"observe",rank:5},
{jp:"絶滅",en:"extinction",rank:5},
{jp:"汚染",en:"pollution",rank:5},
{jp:"洪水",en:"flood",rank:6},
{jp:"地震",en:"earthquake",rank:4},
{jp:"火山",en:"volcano",rank:5},
{jp:"気候",en:"climate",rank:7},
{jp:"酸素",en:"oxygen",rank:7},
{jp:"二酸化炭素",en:"carbon dioxide",rank:6},
{jp:"元素",en:"element",rank:5},
{jp:"細胞",en:"cell",rank:4},
{jp:"器官",en:"organ",rank:5},
{jp:"遺伝子",en:"gene",rank:4},
{jp:"化石",en:"fossil",rank:5},
{jp:"種族",en:"species",rank:5},
{jp:"表面",en:"surface",rank:5},
{jp:"深さ",en:"depth",rank:4},
{jp:"圧力",en:"pressure",rank:6},
{jp:"摩擦",en:"friction",rank:5},
{jp:"観測",en:"observation",rank:5},
{jp:"証拠",en:"evidence",rank:5},

{jp:"環境/自然環境",en:"environment",rank:6},
{jp:"文化/文明",en:"culture",rank:6},
{jp:"氷河",en:"glacier",rank:6},
{jp:"潮",en:"tide",rank:6},
{jp:"交互の/代わりの",en:"alternate",rank:6},
{jp:"利益/利益を得る",en:"profit",rank:6},
{jp:"肥沃な/豊かな",en:"fertile",rank:6},
{jp:"再利用する",en:"recycle",rank:5},
{jp:"消費する/摂取する",en:"consume",rank:6},
{jp:"排出する/解放する",en:"release",rank:5},
{jp:"影響/衝撃",en:"impact",rank:5},
{jp:"地域/地方",en:"region",rank:5},
{jp:"大陸",en:"continent",rank:6},
{jp:"移住する/移動する",en:"migrate",rank:6},
{jp:"適応する/順応する",en:"adapt",rank:5},
{jp:"特徴/機能",en:"feature",rank:7},
{jp:"構造/仕組み",en:"structure",rank:5},
{jp:"機能/関数",en:"function",rank:5},
{jp:"化合物",en:"compound",rank:8},
{jp:"反応/反響",en:"reaction",rank:6},
{jp:"溶液/解決策",en:"solution",rank:5},
{jp:"実験/試み",en:"experiment",rank:6},
{jp:"理論/学説",en:"theory",rank:6},
{jp:"分析する",en:"analyze",rank:5},
{jp:"証明する/立証する",en:"prove",rank:4},

{jp:"民主主義",en:"democracy",rank:7},
{jp:"産業革命",en:"industrial revolution",rank:7},
{jp:"予想する/予報する",en:"forecast",rank:7},
{jp:"管/容器",en:"vessel",rank:7},
{jp:"文明",en:"civilization",rank:8},
{jp:"憲法/体質",en:"constitution",rank:7},
{jp:"政府",en:"government",rank:5},
{jp:"法律/法",en:"law",rank:5},
{jp:"選挙",en:"election",rank:5},
{jp:"革命",en:"revolution",rank:5},
{jp:"植民地",en:"colony",rank:6},
{jp:"独立",en:"independence",rank:6},
{jp:"貿易/取引",en:"trade",rank:4},
{jp:"通貨",en:"currency",rank:5},
{jp:"金融",en:"finance",rank:7},
{jp:"需要/要求",en:"demand",rank:6},
{jp:"供給/供給すること",en:"supply",rank:6},
{jp:"仮説",en:"hypothesis",rank:8},
{jp:"放射線/放射能",en:"radiation",rank:7},
{jp:"重力",en:"gravity",rank:6},
{jp:"軌道/周回軌道",en:"orbit",rank:7},
{jp:"銀河",en:"galaxy",rank:6},
{jp:"宇宙",en:"universe",rank:5},
{jp:"遺伝学",en:"genetics",rank:7},
{jp:"天文学",en:"astronomy",rank:7},
{jp:"生態系",en:"ecosystem",rank:6},
{jp:"多様性",en:"diversity",rank:5},
{jp:"エネルギー",en:"energy",rank:4},
{jp:"物質",en:"matter",rank:6},
{jp:"粒子",en:"particle",rank:6},
{jp:"次元",en:"dimension",rank:6},
{jp:"人工衛星",en:"satellite",rank:6},
{jp:"惑星",en:"planet",rank:4},
{jp:"銀河系",en:"milky way",rank:8},

{jp:"相対性理論",en:"theory of relativity",rank:8},
{jp:"量子力学",en:"quantum mechanics",rank:8},
{jp:"認識論",en:"epistemology",rank:9},
{jp:"決定論",en:"determinism",rank:9},
{jp:"因果関係",en:"causality",rank:9},
{jp:"知覚",en:"perception",rank:9},
{jp:"理性",en:"reason",rank:7},
{jp:"倫理",en:"ethics",rank:7},
{jp:"道徳",en:"morality",rank:6},
{jp:"抽象概念",en:"abstraction",rank:7},
{jp:"主観",en:"subjectivity",rank:8},
{jp:"客観",en:"objectivity",rank:8},
{jp:"実在",en:"reality",rank:6},
{jp:"特異点",en:"singularity",rank:7},

{jp:"意識/自覚",en:"consciousness",rank:9},
{jp:"存在論",en:"ontology",rank:9},
{jp:"経験論",en:"empiricism",rank:8},
{jp:"合理主義",en:"rationalism",rank:9},
{jp:"弁証法",en:"dialectics",rank:10},
{jp:"超越/超越性",en:"transcendence",rank:8},
{jp:"本質/本性",en:"essence",rank:6},
{jp:"現象学",en:"phenomenology",rank:10},
{jp:"宇宙論",en:"cosmology",rank:6},
{jp:"量子もつれ",en:"quantum entanglement",rank:10},
{jp:"パラダイム/規範",en:"paradigm",rank:7},

{jp:"形而上学",en:"metaphysics",rank:10},
{jp:"超弦理論",en:"string theory",rank:10},

{jp:"経験",en:"experience",rank:5},
{jp:"機会",en:"opportunity",rank:7},
{jp:"理由",en:"reason",rank:3},
{jp:"結果",en:"result",rank:3},
{jp:"影響",en:"effect",rank:3},
{jp:"問題(困りごと)",en:"problem",rank:3},
{jp:"意見",en:"opinion",rank:4},
{jp:"状況",en:"situation",rank:5},
{jp:"選択",en:"choice",rank:4},

{jp:"成功",en:"success",rank:3},
{jp:"失敗",en:"failure",rank:5},
{jp:"努力",en:"effort",rank:4},
{jp:"挑戦",en:"challenge",rank:4},
{jp:"変化",en:"change",rank:3},

{jp:"説明する",en:"explain",rank:5},
{jp:"比べる",en:"compare",rank:6},
{jp:"決定する",en:"decide",rank:4},
{jp:"想像する",en:"imagine",rank:4},
{jp:"認める",en:"admit",rank:5},
{jp:"提案する",en:"suggest",rank:5},
{jp:"解決する",en:"solve",rank:4},
{jp:"減る",en:"decrease",rank:5},

{jp:"重要な",en:"important",rank:4},
{jp:"必要な",en:"necessary",rank:5},
{jp:"可能な",en:"possible",rank:4},
{jp:"不可能な",en:"impossible",rank:4},
{jp:"簡単な",en:"simple",rank:5},
{jp:"複雑な",en:"complex",rank:6},
{jp:"正確な",en:"accurate",rank:7},
{jp:"危険な",en:"dangerous",rank:3},

{jp:"社会",en:"society",rank:4},
{jp:"文化",en:"culture",rank:3},
{jp:"歴史",en:"history",rank:3},
{jp:"科学",en:"science",rank:3},
{jp:"技術",en:"technology",rank:4},
{jp:"教育",en:"education",rank:5},
{jp:"環境",en:"environment",rank:5},

{jp:"最近",en:"recently",rank:6},
{jp:"特に",en:"especially",rank:6},
{jp:"実際に",en:"actually",rank:5},
{jp:"ついに",en:"finally",rank:5},
{jp:"おそらく",en:"probably",rank:5},
{jp:"確かに",en:"certainly",rank:6},

{jp:"影響",en:"effect",rank:4},
{jp:"含む",en:"include",rank:5},
{jp:"提供する",en:"provide",rank:6},
{jp:"続ける",en:"continue",rank:5},
{jp:"起こる",en:"occur",rank:6},
{jp:"存在する",en:"exist",rank:5},
{jp:"必要とする",en:"require",rank:6},

{jp:"考える",en:"consider",rank:5},
{jp:"認める",en:"admit",rank:6},
{jp:"示す",en:"indicate",rank:7},
{jp:"表す",en:"represent",rank:6},
{jp:"防ぐ",en:"prevent",rank:6},
{jp:"可能にする",en:"enable",rank:5},
{jp:"選ぶ",en:"select",rank:4},
{jp:"比較する",en:"compare",rank:5},

{jp:"結果",en:"result",rank:4},
{jp:"理由",en:"reason",rank:3},
{jp:"方法",en:"method",rank:4},
{jp:"状況",en:"situation",rank:4},
{jp:"条件",en:"condition",rank:5},
{jp:"効果",en:"effect",rank:5},
{jp:"役割",en:"role",rank:6},
{jp:"利点",en:"advantage",rank:6},
{jp:"欠点",en:"disadvantage",rank:6},

{jp:"重要な",en:"important",rank:3},
{jp:"必要な",en:"necessary",rank:4},
{jp:"適切な",en:"appropriate",rank:5},
{jp:"共通の",en:"common",rank:5},
{jp:"特定の",en:"specific",rank:6},
{jp:"様々な",en:"various",rank:6},
{jp:"一般的な",en:"general",rank:5},
{jp:"個人的な",en:"personal",rank:4},

{jp:"社会",en:"society",rank:5},
{jp:"環境",en:"environment",rank:5},
{jp:"教育",en:"education",rank:5},
{jp:"政府",en:"government",rank:5},
{jp:"人口",en:"population",rank:5},
{jp:"実際に",en:"actually",rank:5},
{jp:"したがって",en:"therefore",rank:7},
{jp:"しかし",en:"however",rank:5},
{jp:"さらに",en:"furthermore",rank:7},
{jp:"なぜなら",en:"because",rank:4},
{jp:"〜にもかかわらず",en:"although",rank:6},
{jp:"改善する",en:"improve",rank:5},
{jp:"発展させる",en:"develop",rank:5},
{jp:"達成する",en:"achieve",rank:6},
{jp:"維持する",en:"maintain",rank:6},
{jp:"戦略",en:"strategy",rank:7},
{jp:"政策",en:"policy",rank:6},
{jp:"市民",en:"citizen",rank:7},
{jp:"共同体",en:"community",rank:5},
{jp:"協力",en:"cooperation",rank:7},
{jp:"対立",en:"conflict",rank:7},
{jp:"自由",en:"freedom",rank:5},
{jp:"正義",en:"justice",rank:5},
{jp:"義務",en:"duty",rank:7},
{jp:"感情",en:"emotion",rank:5},
{jp:"記憶",en:"memory",rank:4},
{jp:"創造性",en:"creativity",rank:6},
{jp:"ネットワーク",en:"network",rank:3},
{jp:"データベース",en:"database",rank:3},
{jp:"アルゴリズム",en:"algorithm",rank:8},
{jp:"暗号化",en:"encryption",rank:9},
{jp:"効率",en:"efficiency",rank:7},
{jp:"生産性",en:"productivity",rank:5},
{jp:"持続する",en:"persist",rank:7},
{jp:"予測する",en:"predict",rank:7},
{jp:"評価する",en:"evaluate",rank:7},


{jp:"いつも",en:"always",rank:3},
{jp:"ときどき",en:"sometimes",rank:3},
{jp:"決して〜ない",en:"never",rank:3},
{jp:"しばしば",en:"often",rank:3},
{jp:"たいてい",en:"usually",rank:3},

{jp:"質問",en:"question",rank:3},
{jp:"答え",en:"answer",rank:3},
{jp:"言葉",en:"word",rank:2},
{jp:"手紙",en:"letter",rank:3},
{jp:"新聞",en:"newspaper",rank:4},
{jp:"辞書",en:"dictionary",rank:4},
{jp:"物語",en:"story",rank:3},
{jp:"音楽",en:"music",rank:2},
{jp:"歌",en:"song",rank:2},
{jp:"映画",en:"movie",rank:2},

{jp:"店",en:"shop",rank:2},
{jp:"市場",en:"market",rank:4},
{jp:"道",en:"road",rank:2},
{jp:"交差点",en:"crossroad",rank:5},
{jp:"建物(ビル)",en:"building",rank:3},

{jp:"料理",en:"cooking",rank:3},
{jp:"朝食",en:"breakfast",rank:3},
{jp:"昼食",en:"lunch",rank:3},
{jp:"夕食",en:"dinner",rank:3},
{jp:"野菜",en:"vegetable",rank:4},
{jp:"果物",en:"fruit",rank:3},
{jp:"肉",en:"meat",rank:3},
{jp:"魚",en:"fish",rank:2},

{jp:"泳ぐ",en:"swim",rank:2},
{jp:"歌う",en:"sing",rank:2},
{jp:"話す(言語を話す)",en:"speak",rank:2},
{jp:"話す(会話する)",en:"talk",rank:2},
{jp:"教える",en:"teach",rank:2},
{jp:"使う",en:"use",rank:2},
{jp:"開ける",en:"open",rank:2},
{jp:"閉める",en:"close",rank:2},
{jp:"待つ",en:"wait",rank:2},
{jp:"借りる",en:"borrow",rank:4},
{jp:"貸す",en:"lend",rank:3},

{jp:"うれしい",en:"happy",rank:2},
{jp:"悲しい",en:"sad",rank:2},
{jp:"忙しい",en:"busy",rank:2},
{jp:"有名な",en:"famous",rank:3},
{jp:"親切な",en:"kind",rank:2},
{jp:"静かな",en:"quiet",rank:4},
{jp:"騒がしい",en:"noisy",rank:4},
{jp:"美しい",en:"beautiful",rank:3},

{jp:"もし〜なら",en:"if",rank:4},
{jp:"だから",en:"so",rank:4},
{jp:"そして",en:"and",rank:2},
{jp:"または",en:"or",rank:2},
{jp:"でも",en:"but",rank:2},
{jp:"たぶん",en:"maybe",rank:4},



{jp:"空港",en:"airport",rank:3},
{jp:"銀行",en:"bank",rank:3},
{jp:"図書館",en:"library",rank:3},
{jp:"博物館",en:"museum",rank:3},
{jp:"レストラン",en:"restaurant",rank:3},
{jp:"プール",en:"pool",rank:2},
{jp:"試合",en:"game",rank:2},
{jp:"チーム",en:"team",rank:2},
{jp:"趣味",en:"hobby",rank:4},
{jp:"夢",en:"dream",rank:3},

{jp:"宿題",en:"homework",rank:2},
{jp:"授業",en:"class",rank:2},
{jp:"教科書",en:"textbook",rank:3},
{jp:"ノート",en:"notebook",rank:2},

{jp:"買う",en:"buy",rank:2},
{jp:"売る",en:"sell",rank:2},
{jp:"送る",en:"send",rank:3},
{jp:"受け取る",en:"receive",rank:4},
{jp:"訪れる",en:"visit",rank:2},
{jp:"会う(約束・初対面)",en:"meet",rank:2},
{jp:"会う(訪問する)",en:"see",rank:4},
{jp:"練習する",en:"practice",rank:3},
{jp:"選ぶ",en:"choose",rank:3},
{jp:"忘れる",en:"forget",rank:3},

{jp:"人気のある",en:"popular",rank:3},
{jp:"特別な",en:"special",rank:3},
{jp:"大切な",en:"important",rank:3},
{jp:"違う",en:"different",rank:3},
{jp:"同じ",en:"same",rank:3},
{jp:"十分な",en:"enough",rank:4},

{jp:"みんな",en:"everyone",rank:3},
{jp:"誰か",en:"someone",rank:3},
{jp:"誰も〜ない",en:"no one",rank:4},
{jp:"何か",en:"something",rank:3},
{jp:"何も〜ない",en:"nothing",rank:4},

{jp:"前に",en:"before",rank:3},
{jp:"後で",en:"after",rank:3},
{jp:"すぐに",en:"soon",rank:3},
{jp:"すでに",en:"already",rank:4},
{jp:"まだ",en:"yet",rank:4},
{jp:"ちょうど",en:"just",rank:4},

{jp:"必要とする",en:"need",rank:2},
{jp:"望む",en:"hope",rank:3},
{jp:"計画する",en:"plan",rank:4},
{jp:"約束",en:"promise",rank:5},
{jp:"招待する",en:"invite",rank:4},
{jp:"紹介する",en:"introduce",rank:5},
{jp:"準備する",en:"prepare",rank:5},
{jp:"到着する",en:"arrive",rank:3},



{jp:"経験",en:"experience",rank:4},
{jp:"活動",en:"activity",rank:4},
{jp:"会話",en:"conversation",rank:4},
{jp:"文化祭",en:"festival",rank:5},
{jp:"大会",en:"tournament",rank:5},
{jp:"旅行者",en:"traveler",rank:4},
{jp:"案内",en:"guide",rank:4},
{jp:"景色",en:"view",rank:3},
{jp:"伝統",en:"tradition",rank:5},
{jp:"習慣",en:"custom",rank:6},

{jp:"成功する",en:"succeed",rank:4},
{jp:"失敗する",en:"fail",rank:4},
{jp:"改善する",en:"improve",rank:5},
{jp:"発見する",en:"discover",rank:4},
{jp:"参加する",en:"join",rank:3},
{jp:"参加する",en:"participate",rank:5},
{jp:"助ける",en:"help",rank:2},
{jp:"支援する",en:"support",rank:5},
{jp:"共有する",en:"share",rank:4},
{jp:"達成する",en:"achieve",rank:5},

{jp:"危険な",en:"risky",rank:5},
{jp:"健康な",en:"healthy",rank:4},
{jp:"便利な",en:"convenient",rank:5},
{jp:"不便な",en:"inconvenient",rank:6},
{jp:"活発な",en:"active",rank:4},
{jp:"受け身の",en:"passive",rank:6},
{jp:"興味深い",en:"interesting",rank:3},
{jp:"退屈な",en:"boring",rank:4},
{jp:"素晴らしい",en:"wonderful",rank:5},

{jp:"誰でも",en:"anyone",rank:4},
{jp:"何でも",en:"anything",rank:4},
{jp:"どこでも",en:"anywhere",rank:4},
{jp:"全て",en:"everything",rank:4},
{jp:"至る所で",en:"everywhere",rank:5},

{jp:"一緒に",en:"together",rank:3},
{jp:"別々に",en:"separately",rank:6},
{jp:"突然",en:"suddenly",rank:5},
{jp:"ゆっくり",en:"slowly",rank:3},
{jp:"慎重に",en:"carefully",rank:4},
{jp:"簡単に",en:"easily",rank:4},
{jp:"本当に",en:"truly",rank:5},
{jp:"幸運にも",en:"luckily",rank:5},
{jp:"残念ながら",en:"unfortunately",rank:6},

{jp:"〜の間",en:"during",rank:5},
{jp:"〜以来",en:"since",rank:4},
{jp:"〜まで",en:"until",rank:4},
{jp:"〜なしで",en:"without",rank:4},
{jp:"〜に対して",en:"against",rank:6},
{jp:"〜を通して",en:"through",rank:5},
{jp:"〜の中へ",en:"into",rank:3},

{jp:"危険(実際の状態)",en:"danger",rank:4},
{jp:"危険性",en:"risk",rank:5},

{jp:"事実(客観的)",en:"fact",rank:4},
{jp:"真実(本当のこと)",en:"truth",rank:5},

{jp:"利益(得られる良いこと)",en:"benefit",rank:7},
{jp:"価値(重要さ・値打ち)",en:"value",rank:5},

{jp:"旅行(一般概念)",en:"travel",rank:2},
{jp:"旅行(1回の旅)",en:"trip",rank:3},

{jp:"借りる",en:"borrow",rank:4},
{jp:"貸す",en:"lend",rank:3},

{jp:"持ってくる(話し手へ)",en:"bring",rank:4},
{jp:"持っていく(話し手から離れる)",en:"take",rank:2},

{jp:"探す",en:"look for",rank:3},
{jp:"見つける",en:"find",rank:2},

{jp:"覚えている",en:"remember",rank:4},
{jp:"忘れる",en:"forget",rank:3},

{jp:"到着する(比較的よく使う)",en:"arrive",rank:3},
{jp:"到達する(目的地に着く)",en:"reach",rank:5},
{jp:"近くの",en:"near",rank:3},
{jp:"遠い",en:"far",rank:3},
{jp:"向かい側に",en:"across",rank:4},

{jp:"出席する",en:"attend",rank:5},
{jp:"卒業する",en:"graduate",rank:4},
{jp:"入学する",en:"enter",rank:5},

{jp:"世話",en:"care",rank:4},
{jp:"世話人",en:"caretaker",rank:6},

{jp:"育てる",en:"raise",rank:5},
{jp:"育つ",en:"grow",rank:3},

{jp:"減らす",en:"reduce",rank:4},

{jp:"選手",en:"player",rank:3},
{jp:"観客",en:"audience",rank:5},
{jp:"観光客(観光客のみ)",en:"tourist",rank:4},

{jp:"田舎",en:"countryside",rank:6},
{jp:"都会",en:"city",rank:3},
{jp:"首都",en:"capital",rank:5},

{jp:"交通",en:"traffic",rank:4},
{jp:"乗り物",en:"vehicle",rank:6},
{jp:"自転車",en:"bicycle",rank:3},

{jp:"現金",en:"cash",rank:4},
{jp:"価格(値段)",en:"price",rank:4},
{jp:"未来の",en:"future",rank:3},
{jp:"現在の",en:"current",rank:5},
{jp:"過去の",en:"past",rank:4},

{jp:"外国人",en:"foreigner",rank:4},
{jp:"言語",en:"language",rank:3},
{jp:"発音",en:"pronunciation",rank:8},

{jp:"伝える",en:"tell",rank:2},
{jp:"知らせる",en:"inform",rank:6},
{jp:"報告する",en:"report",rank:5},

{jp:"賞(受賞するもの)",en:"award",rank:5},
{jp:"賞品",en:"prize",rank:4},

{jp:"再生可能な",en:"renewable",rank:6},

{jp:"海外",en:"overseas",rank:5},
{jp:"国際的な",en:"international",rank:5},

{jp:"意見を述べる",en:"express",rank:6},
{jp:"賛成する",en:"agree",rank:3},
{jp:"反対する",en:"disagree",rank:5},

{jp:"決心する",en:"decide",rank:4},
{jp:"選択肢",en:"option",rank:5},
{jp:"判断",en:"decision",rank:5},

{jp:"挑戦する",en:"challenge",rank:4},
{jp:"紹介する",en:"introduce",rank:5},
{jp:"準備する",en:"prepare",rank:4},
{jp:"続ける",en:"continue",rank:4},
{jp:"止める(やめる)",en:"stop",rank:2},
{jp:"止める(中断する)",en:"pause",rank:5},

{jp:"説明",en:"explanation",rank:5},
{jp:"提案",en:"suggestion",rank:5},
{jp:"約束",en:"promise",rank:4},
{jp:"秘密",en:"secret",rank:3},
{jp:"間違い",en:"mistake",rank:3},
{jp:"成功者",en:"winner",rank:4},

{jp:"機会(チャンス)",en:"chance",rank:4},
{jp:"機会(好機)",en:"opportunity",rank:6},

{jp:"勝者",en:"winner",rank:3},
{jp:"敗者",en:"loser",rank:4},

{jp:"情報",en:"information",rank:5},
{jp:"知識",en:"knowledge",rank:6},
{jp:"助言",en:"advice",rank:4},

{jp:"声",en:"voice",rank:3},
{jp:"音",en:"sound",rank:3},
{jp:"騒音",en:"noise",rank:4},

{jp:"地面",en:"ground",rank:3},
{jp:"床",en:"floor",rank:3},

{jp:"宇宙",en:"space",rank:3},

{jp:"場所(一般)",en:"place",rank:2},
{jp:"場所(位置)",en:"location",rank:6},

{jp:"終点",en:"goal",rank:4},
{jp:"目標",en:"target",rank:5},

{jp:"制服(学校など)",en:"uniform",rank:4},
{jp:"衣服",en:"clothing",rank:5},

{jp:"乗客",en:"passenger",rank:6},
{jp:"運転手",en:"driver",rank:3},

{jp:"習慣",en:"habit",rank:4},
{jp:"伝統的習慣",en:"custom",rank:6},

{jp:"地元の",en:"local",rank:4},
{jp:"外国の",en:"foreign",rank:4},

{jp:"安全な",en:"safe",rank:3},

{jp:"健康",en:"health",rank:3},

{jp:"親",en:"parent",rank:3},
{jp:"親戚",en:"relative",rank:4},

{jp:"普通の",en:"ordinary",rank:4},
{jp:"特別な",en:"special",rank:3},

{jp:"正しい",en:"correct",rank:3},
{jp:"正しい(道徳的に)",en:"right",rank:4},

{jp:"間違った",en:"wrong",rank:3},
{jp:"誤った",en:"incorrect",rank:6},

  
{jp:"無謀な",en:"reckless",rank:6},
{jp:"骨盤",en:"pelvis",rank:6},
{jp:"降りる/受け継がせる",en:"descend",rank:6},
{jp:"ミツバチの巣",en:"hive",rank:5},
{jp:"逆も同様である",en:"vice versa",rank:10},
{jp:"農業",en:"agriculture",rank:6},
{jp:"小麦",en:"wheat",rank:5},

{jp:"証言する",en:"testify",rank:5},
{jp:"契約",en:"contract",rank:5},
{jp:"例外",en:"exception",rank:6},
{jp:"固守/付着",en:"adherence",rank:7},
{jp:"従う",en:"abide",rank:6},
{jp:"特許",en:"patent",rank:5},
{jp:"殺人",en:"murder",rank:5},
{jp:"逮捕する",en:"arrest",rank:4},
{jp:"犯罪",en:"crime",rank:5},
{jp:"刑務所",en:"jail",rank:6},
{jp:"違反/反則",en:"violation",rank:5},
{jp:"実り多い",en:"fruitful",rank:5},
{jp:"統合する/合成する",en:"synthesize",rank:7},
{jp:"集中的な",en:"intensive",rank:6},
{jp:"目新しい/小説",en:"novel",rank:4},
{jp:"熟考する",en:"ponder",rank:7},
{jp:"洞察力",en:"insight",rank:6},
{jp:"証言する",en:"testify",rank:5},
{jp:"例外",en:"exception",rank:6},
{jp:"遵守",en:"adherence",rank:7},
{jp:"従う",en:"abide",rank:6},
{jp:"特許",en:"patent",rank:5},
{jp:"殺人",en:"murder",rank:5},
{jp:"逮捕",en:"arrest",rank:4},
{jp:"犯罪者",en:"criminal",rank:5},
{jp:"刑務所",en:"jail",rank:6},
{jp:"違反",en:"violation",rank:5},
{jp:"悪名高い",en:"notorious",rank:6},
{jp:"統合する",en:"synthesize",rank:7},
{jp:"集中的な",en:"intensive",rank:6},
{jp:"斬新な",en:"novel",rank:4},
{jp:"革新",en:"innovation",rank:5},
{jp:"熟考する",en:"ponder",rank:7},
{jp:"洞察",en:"insight",rank:6},
{jp:"彫刻家",en:"sculptor",rank:7},
{jp:"骨董品",en:"antique",rank:6},
{jp:"粘土",en:"clay",rank:5},
{jp:"版(新旧)",en:"version",rank:4},
{jp:"詩人",en:"poet",rank:5},
{jp:"批評",en:"criticism",rank:5},
{jp:"編集する",en:"edit",rank:4},
{jp:"放棄する",en:"abandon",rank:5},
{jp:"処分する",en:"dispose",rank:5},
{jp:"遅い",en:"late",rank:3},
{jp:"衝突する",en:"crash",rank:4},
{jp:"漏れる",en:"leak",rank:4},
{jp:"主張する",en:"claim",rank:5},
{jp:"強調する",en:"highlight",rank:4},
{jp:"暴動",en:"riot",rank:6},
{jp:"正式な",en:"formal",rank:5},
{jp:"繊細な",en:"delicate",rank:4},
{jp:"合理的な",en:"rational",rank:6},
{jp:"全体の",en:"entire",rank:5},
{jp:"多数の(数量)",en:"numerous",rank:5},
{jp:"複数の(倍数)",en:"multiple",rank:5},
{jp:"規模",en:"scale",rank:4},
{jp:"最大",en:"maximum",rank:4},
{jp:"最小",en:"minimum",rank:4},
{jp:"わずかな",en:"slight",rank:6},
{jp:"混沌",en:"chaos",rank:7},
{jp:"恐怖",en:"dread",rank:6},
{jp:"冷静",en:"calm",rank:6},
{jp:"国",en:"country",rank:4},
{jp:"縫う",en:"sew",rank:5},
{jp:"注ぐ",en:"pour",rank:4},
{jp:"倫理",en:"ethics",rank:5},
{jp:"熱意",en:"enthusiasm",rank:8},
{jp:"建築家",en:"architect",rank:5},
{jp:"計画",en:"scheme",rank:7},
{jp:"巨大な",en:"gigantic",rank:5},
{jp:"辞職する",en:"resign",rank:5},
{jp:"誇張する",en:"exaggerate",rank:7},
{jp:"実行する",en:"execute",rank:6},
{jp:"贅沢",en:"luxury",rank:6},
{jp:"裸の",en:"naked",rank:5},
{jp:"微妙な",en:"subtle",rank:7},
{jp:"侮辱する",en:"insult",rank:7},
{jp:"抗議する",en:"protest",rank:5},
{jp:"同意",en:"consent",rank:5},
{jp:"費用",en:"expense",rank:6},
{jp:"征服する",en:"conquer",rank:6},
{jp:"明確に異なる",en:"distinct",rank:6},
{jp:"誠実な",en:"sincere",rank:6},
{jp:"簡潔な",en:"concise",rank:6},
{jp:"帝国",en:"empire",rank:6},
{jp:"地域",en:"region",rank:5},
{jp:"海の",en:"marine",rank:5},
{jp:"巨大な",en:"enormous",rank:5},
{jp:"妥協",en:"compromise",rank:7},
{jp:"技術者",en:"engineer",rank:4},
{jp:"半径",en:"radius",rank:7},
{jp:"直径",en:"diameter",rank:5},
{jp:"勤勉な",en:"diligent",rank:7},
{jp:"永続的な",en:"permanent",rank:5},
{jp:"職業",en:"profession",rank:6},
{jp:"受験者",en:"examinee",rank:7},
{jp:"原則",en:"principle",rank:6},
{jp:"動機",en:"motivation",rank:3},
{jp:"適性",en:"aptitude",rank:7},
{jp:"かけがえのない",en:"irreplaceable",rank:8},
{jp:"兄弟姉妹",en:"sibling",rank:6},
{jp:"英雄",en:"hero",rank:4},
{jp:"ヒロイン",en:"heroine",rank:4},
{jp:"著者",en:"author",rank:7},
{jp:"間違いなく",en:"definitely",rank:6},
{jp:"絶対に",en:"absolutely",rank:7},
{jp:"同様に",en:"likewise",rank:6},
{jp:"正確に",en:"precisely",rank:7},
{jp:"羨望",en:"envy",rank:5},
{jp:"運",en:"luck",rank:4},
{jp:"賭ける",en:"bet",rank:4},
{jp:"憎む",en:"hate",rank:4},
{jp:"簡潔な",en:"brief",rank:5},
{jp:"しるし",en:"token",rank:6},
{jp:"分割する",en:"split",rank:5},
{jp:"明確にする",en:"clarify",rank:7},
{jp:"偶然の一致",en:"coincidence",rank:9},
{jp:"～しなければならない",en:"must",rank:4},
{jp:"奇妙な",en:"weird",rank:7},
{jp:"予想外の",en:"unexpected",rank:5},
{jp:"4分の1",en:"quarter",rank:5},
{jp:"破裂する",en:"burst",rank:5},
{jp:"レシピ",en:"recipe",rank:4},
{jp:"喉が渇いた",en:"thirsty",rank:5},
{jp:"狭い",en:"narrow",rank:5},
{jp:"憂鬱",en:"melancholy",rank:8},
{jp:"吐く",en:"vomit",rank:6},
{jp:"曖昧な",en:"vague",rank:8},
{jp:"揺れる",en:"swing",rank:6},
{jp:"貴重な",en:"precious",rank:6},
{jp:"犠牲",en:"sacrifice",rank:7},
{jp:"抱きしめる",en:"hug",rank:3},
{jp:"小屋",en:"cottage",rank:5},
{jp:"取りつく",en:"haunt",rank:6},
{jp:"薬局",en:"pharmacy",rank:7},
{jp:"期限切れになる",en:"expire",rank:6},
{jp:"怒らせる",en:"offend",rank:5},
{jp:"気分",en:"mood",rank:4},
{jp:"わずかに",en:"slightly",rank:6},
{jp:"宣言する",en:"declare",rank:6},
{jp:"有効な",en:"valid",rank:7},
{jp:"遠足",en:"excursion",rank:6},
{jp:"赤道",en:"equator",rank:5},
{jp:"半島",en:"peninsula",rank:5},
{jp:"広場",en:"square",rank:4},
{jp:"警報を出す(知らせる)",en:"alert",rank:4},
{jp:"交換する",en:"exchange",rank:5},
{jp:"異国風の",en:"exotic",rank:5},
{jp:"出発",en:"departure",rank:6},
{jp:"縛る",en:"bind",rank:4},
{jp:"宿屋",en:"inn",rank:5},
{jp:"地下室",en:"basement",rank:6},
{jp:"土産",en:"souvenir",rank:5},
{jp:"札",en:"tag",rank:4},
{jp:"予算",en:"budget",rank:6},
{jp:"信用",en:"credit",rank:5},
{jp:"カラオケ",en:"karaoke",rank:3},
{jp:"禁止する",en:"ban",rank:4},
{jp:"統治する",en:"reign",rank:7},
{jp:"仏塔",en:"pagoda",rank:8},
{jp:"城",en:"castle",rank:3},
{jp:"墓",en:"tomb",rank:5},
{jp:"太平洋",en:"pacific",rank:5},
{jp:"大西洋",en:"atlantic",rank:5},
{jp:"諸島",en:"archipelago",rank:9},
{jp:"谷",en:"valley",rank:5},
{jp:"高度",en:"altitude",rank:5},
{jp:"漆",en:"lacquer",rank:10},
{jp:"頂上",en:"top",rank:4},
{jp:"発酵する",en:"ferment",rank:6},
{jp:"放射線",en:"radiation",rank:6},
{jp:"名声",en:"prestige",rank:6},
{jp:"咲く",en:"bloom",rank:5},
{jp:"オーガ",en:"ogre",rank:7},
{jp:"特徴",en:"feature",rank:5},
{jp:"二重の",en:"double",rank:4},
{jp:"変動する",en:"fluctuate",rank:7},
{jp:"水準",en:"level",rank:5},
{jp:"調査",en:"survey",rank:5},
{jp:"分析する",en:"analyze",rank:5},
{jp:"比較する",en:"compare",rank:5},
{jp:"軸",en:"axis",rank:7},
{jp:"単位",en:"unit",rank:5},
{jp:"カテゴリ",en:"category",rank:6},
{jp:"需要",en:"demand",rank:5},
{jp:"率",en:"rate",rank:4},
{jp:"程度",en:"degree",rank:5},
{jp:"研究",en:"research",rank:5},
{jp:"差",en:"gap",rank:4},
{jp:"記録",en:"record",rank:5},
{jp:"目指す",en:"aim",rank:4},
{jp:"垂直の",en:"vertical",rank:5},
{jp:"以前の",en:"former",rank:5},
{jp:"ランダムな",en:"random",rank:4},
{jp:"毎年の",en:"annual",rank:6},
{jp:"安定した",en:"stable",rank:6},
{jp:"おおよそ",en:"approximately",rank:10},
{jp:"貼り付ける",en:"paste",rank:4},
{jp:"飛ばす(後戻り可能)",en:"skip",rank:4},
{jp:"つかむ",en:"grab",rank:4},
{jp:"握る",en:"grip",rank:4},
{jp:"伸ばす",en:"stretch",rank:4},
{jp:"目覚めている",en:"awake",rank:4},
{jp:"ホッチキス",en:"stapler",rank:4},
{jp:"ひざまずく",en:"kneel",rank:7},
{jp:"調子",en:"tune",rank:6},
{jp:"掃く",en:"sweep",rank:5},
{jp:"ささやく",en:"whisper",rank:6},
{jp:"急ぐこと",en:"haste",rank:6},
{jp:"列",en:"queue",rank:5},
{jp:"悪夢",en:"nightmare",rank:5},
{jp:"預金",en:"deposit",rank:6},
{jp:"拍手する",en:"clap",rank:4},
{jp:"こする",en:"scrub",rank:5},
{jp:"染める",en:"dye",rank:5},
{jp:"香水",en:"perfume",rank:5},
{jp:"避難所",en:"refuge",rank:5},
{jp:"挿入する",en:"insert",rank:5},
{jp:"ひっかく",en:"scratch",rank:5},
{jp:"コード",en:"code",rank:4},
{jp:"端",en:"edge",rank:4},
{jp:"蓄積する",en:"accumulate",rank:7},
{jp:"商業の",en:"commercial",rank:4},
{jp:"従う",en:"conform",rank:6},
{jp:"スタジオ",en:"studio",rank:4},
{jp:"立ち退く",en:"vacate",rank:5},
{jp:"散らかり",en:"mess",rank:6},
{jp:"散らばらせる",en:"scatter",rank:5},
{jp:"控える",en:"refrain",rank:6},
{jp:"達成する",en:"achieve",rank:5},
{jp:"前進",en:"advance",rank:5},
{jp:"無駄な",en:"vain",rank:5},
{jp:"思い出す(意識的に)",en:"recall",rank:5},
{jp:"思い出す(他者によって)",en:"remind",rank:5},
{jp:"変形させる",en:"transform",rank:5},
{jp:"花束",en:"bouquet",rank:9},
{jp:"突き刺す",en:"pierce",rank:5},
{jp:"行為",en:"deed",rank:5},
{jp:"欠陥",en:"flaw",rank:6},
{jp:"利用する",en:"utilize",rank:6},
{jp:"わな",en:"trap",rank:4},
{jp:"華氏",en:"Fahrenheit",rank:8},
{jp:"摂氏",en:"Celsius",rank:5},
{jp:"障害",en:"obstacle",rank:6},
{jp:"逆転する",en:"reverse",rank:5},
];